### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by JoergFF** [vicimikec/ViciPhone#3]
Hi,

please add the German translation.

CU
Jörg

[german.zip](https://github.com/vicimikec/ViciPhone/files/4986126/german.zip)

**Comment by ccabrerar** [comment]
I've already added your code under my own fork https://github.com/ccabrerar/ViciPhone

**Comment by JoergFF** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hello Christian,


Am Montag, den 27.07.2020, 22:47 -0700 schrieb Christian Cabrera:
> I've already added your code under my own fork https://github.com/ccabrerar/ViciPhone
> 
[...]
Many thanks.


CU
Jörg

- -- 
New:
GPG Fingerprint: 4443 9C15 A011 0C89 2EA8  1E9D E2E1 3D93 1842 DAC7
GPG key        : DECFAACFC681D824 

Jörg Frings-Fürst
D-54470 Lieser

git:      https://jff.email/cgit/

Threema: SYR8SJXB
Wire: @joergfringsfuerst
Skype: joergpenguin
Ring:     jff
Telegram: @joergfringsfuerst
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEEREOcFaARDIkuqB6d4uE9kxhC2scFAl8f310ACgkQ4uE9kxhC
2sdoGAwAmbQHR5vXk3UdzZBzFcAOakGHje00nGWJFgycZaM24uVKjU8m6rY/MasH
9VI8nTQZas0OrSydW1QMNZAdSmK0PiIh6nYH8tuYuviKq7afZC0Iny8PTaDbEYF4
/M145SuVIudFQ9AFVkjecDzcpoad1919aXFij+E9bqnJCj077Gd3nc0fFOMisvg9
34sH/HKyuAOfj7ZDeCTHtqWrauzVpzdFruBCyLfQNtiR/SzpCEycFFebwQvQJmWG
y+fdZJxQDWOnfua1/GHePocVhTva6FAKPsmM62AJX3nb0X427YmlJxNjSIyWYwxy
7cb3ZCMGqTU1bAJp7xWzdmdrSSlYMdihI/+VubiSg8Lize5Im7E8khPt6MVVAKvy
+ytyrHILboVPbRNhxKbWHUYA8a7krvOQg/Gt1XJWX0W2HxAsDq9Xg2hskj+hW7DW
wWOuYhikqnZXbeIi7hKDa5i2kJAekmN8DUBSPDwy55COhyRxvG1W0lTRtHwOY1r+
doXVdeze
=rauv
-----END PGP SIGNATURE-----
